name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl git make perl clang ldid dpkg fakeroot zip unzip

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build tweak
        run: |
          make clean package
        env:
          THEOS: ${{ env.THEOS }}

      - name: Upload deb file
        uses: actions/upload-artifact@v4
        with:
          name: tweak-deb
          path: ./packages/*.deb